// Generated by gencpp from file video_recorder/cam_controlResponse.msg
// DO NOT EDIT!


#ifndef VIDEO_RECORDER_MESSAGE_CAM_CONTROLRESPONSE_H
#define VIDEO_RECORDER_MESSAGE_CAM_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace video_recorder
{
template <class ContainerAllocator>
struct cam_controlResponse_
{
  typedef cam_controlResponse_<ContainerAllocator> Type;

  cam_controlResponse_()
    : ack(0)  {
    }
  cam_controlResponse_(const ContainerAllocator& _alloc)
    : ack(0)  {
  (void)_alloc;
    }



   typedef int16_t _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::video_recorder::cam_controlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::video_recorder::cam_controlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cam_controlResponse_

typedef ::video_recorder::cam_controlResponse_<std::allocator<void> > cam_controlResponse;

typedef boost::shared_ptr< ::video_recorder::cam_controlResponse > cam_controlResponsePtr;
typedef boost::shared_ptr< ::video_recorder::cam_controlResponse const> cam_controlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::video_recorder::cam_controlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::video_recorder::cam_controlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace video_recorder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::video_recorder::cam_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::video_recorder::cam_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::video_recorder::cam_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::video_recorder::cam_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::video_recorder::cam_controlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::video_recorder::cam_controlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::video_recorder::cam_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efd27fb04e2a6ce3c9ff1f47eb32e7bb";
  }

  static const char* value(const ::video_recorder::cam_controlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefd27fb04e2a6ce3ULL;
  static const uint64_t static_value2 = 0xc9ff1f47eb32e7bbULL;
};

template<class ContainerAllocator>
struct DataType< ::video_recorder::cam_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "video_recorder/cam_controlResponse";
  }

  static const char* value(const ::video_recorder::cam_controlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::video_recorder::cam_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ack\n\
\n\
";
  }

  static const char* value(const ::video_recorder::cam_controlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::video_recorder::cam_controlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cam_controlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::video_recorder::cam_controlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::video_recorder::cam_controlResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIDEO_RECORDER_MESSAGE_CAM_CONTROLRESPONSE_H
