// Generated by gencpp from file video_recorder/cam_controlRequest.msg
// DO NOT EDIT!


#ifndef VIDEO_RECORDER_MESSAGE_CAM_CONTROLREQUEST_H
#define VIDEO_RECORDER_MESSAGE_CAM_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace video_recorder
{
template <class ContainerAllocator>
struct cam_controlRequest_
{
  typedef cam_controlRequest_<ContainerAllocator> Type;

  cam_controlRequest_()
    : settings()  {
    }
  cam_controlRequest_(const ContainerAllocator& _alloc)
    : settings(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _settings_type;
  _settings_type settings;





  typedef boost::shared_ptr< ::video_recorder::cam_controlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::video_recorder::cam_controlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cam_controlRequest_

typedef ::video_recorder::cam_controlRequest_<std::allocator<void> > cam_controlRequest;

typedef boost::shared_ptr< ::video_recorder::cam_controlRequest > cam_controlRequestPtr;
typedef boost::shared_ptr< ::video_recorder::cam_controlRequest const> cam_controlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::video_recorder::cam_controlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::video_recorder::cam_controlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace video_recorder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::video_recorder::cam_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::video_recorder::cam_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::video_recorder::cam_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::video_recorder::cam_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::video_recorder::cam_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::video_recorder::cam_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::video_recorder::cam_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adaefbda6e892ce0da5d70a54c9e569a";
  }

  static const char* value(const ::video_recorder::cam_controlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadaefbda6e892ce0ULL;
  static const uint64_t static_value2 = 0xda5d70a54c9e569aULL;
};

template<class ContainerAllocator>
struct DataType< ::video_recorder::cam_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "video_recorder/cam_controlRequest";
  }

  static const char* value(const ::video_recorder::cam_controlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::video_recorder::cam_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string settings\n\
";
  }

  static const char* value(const ::video_recorder::cam_controlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::video_recorder::cam_controlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.settings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cam_controlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::video_recorder::cam_controlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::video_recorder::cam_controlRequest_<ContainerAllocator>& v)
  {
    s << indent << "settings: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.settings);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIDEO_RECORDER_MESSAGE_CAM_CONTROLREQUEST_H
