gantry:
    devname: '/dev/ttyACM0' # [device string]
    baudrate: 115200        # [baud]
    traj_folder: 'test_NewTraj'   #[folder string]
    num_reps: 1             #[number]
    hand_actuation: 'gcode' #[string] OPTIONS - 'gcode', 'standalone'

object_return: 
    devname: '/dev/ttyUSB0' # [device string]
    baudrate: 115200        # [baud]
    default_delay: 1000     # [ms]

camera1: 
    devname: '/dev/video0'  #[device string]
    location: 'Front'       #[string]
    picture_width: 1920     #[px]
    picture_height: 1080    #[px]

cameras_on: 1
