// Generated by gencpp from file serial_test/SerialSend.msg
// DO NOT EDIT!


#ifndef SERIAL_TEST_MESSAGE_SERIALSEND_H
#define SERIAL_TEST_MESSAGE_SERIALSEND_H

#include <ros/service_traits.h>


#include <serial_test/SerialSendRequest.h>
#include <serial_test/SerialSendResponse.h>


namespace serial_test
{

struct SerialSend
{

typedef SerialSendRequest Request;
typedef SerialSendResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialSend
} // namespace serial_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serial_test::SerialSend > {
  static const char* value()
  {
    return "4a85f0858e5941ef92944e5dd453320b";
  }

  static const char* value(const ::serial_test::SerialSend&) { return value(); }
};

template<>
struct DataType< ::serial_test::SerialSend > {
  static const char* value()
  {
    return "serial_test/SerialSend";
  }

  static const char* value(const ::serial_test::SerialSend&) { return value(); }
};


// service_traits::MD5Sum< ::serial_test::SerialSendRequest> should match 
// service_traits::MD5Sum< ::serial_test::SerialSend > 
template<>
struct MD5Sum< ::serial_test::SerialSendRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serial_test::SerialSend >::value();
  }
  static const char* value(const ::serial_test::SerialSendRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_test::SerialSendRequest> should match 
// service_traits::DataType< ::serial_test::SerialSend > 
template<>
struct DataType< ::serial_test::SerialSendRequest>
{
  static const char* value()
  {
    return DataType< ::serial_test::SerialSend >::value();
  }
  static const char* value(const ::serial_test::SerialSendRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serial_test::SerialSendResponse> should match 
// service_traits::MD5Sum< ::serial_test::SerialSend > 
template<>
struct MD5Sum< ::serial_test::SerialSendResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serial_test::SerialSend >::value();
  }
  static const char* value(const ::serial_test::SerialSendResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_test::SerialSendResponse> should match 
// service_traits::DataType< ::serial_test::SerialSend > 
template<>
struct DataType< ::serial_test::SerialSendResponse>
{
  static const char* value()
  {
    return DataType< ::serial_test::SerialSend >::value();
  }
  static const char* value(const ::serial_test::SerialSendResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_TEST_MESSAGE_SERIALSEND_H
