// Generated by gencpp from file serial_test/serial_sendRequest.msg
// DO NOT EDIT!


#ifndef SERIAL_TEST_MESSAGE_SERIAL_SENDREQUEST_H
#define SERIAL_TEST_MESSAGE_SERIAL_SENDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_test
{
template <class ContainerAllocator>
struct serial_sendRequest_
{
  typedef serial_sendRequest_<ContainerAllocator> Type;

  serial_sendRequest_()
    : command(0)  {
    }
  serial_sendRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef int16_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::serial_test::serial_sendRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_test::serial_sendRequest_<ContainerAllocator> const> ConstPtr;

}; // struct serial_sendRequest_

typedef ::serial_test::serial_sendRequest_<std::allocator<void> > serial_sendRequest;

typedef boost::shared_ptr< ::serial_test::serial_sendRequest > serial_sendRequestPtr;
typedef boost::shared_ptr< ::serial_test::serial_sendRequest const> serial_sendRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_test::serial_sendRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_test::serial_sendRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'serial_test': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/serial_test/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_test::serial_sendRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_test::serial_sendRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_test::serial_sendRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_test::serial_sendRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_test::serial_sendRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_test::serial_sendRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_test::serial_sendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e9e8174f74cb4650ecb20cd2f2bf4c3";
  }

  static const char* value(const ::serial_test::serial_sendRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e9e8174f74cb465ULL;
  static const uint64_t static_value2 = 0x0ecb20cd2f2bf4c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_test::serial_sendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_test/serial_sendRequest";
  }

  static const char* value(const ::serial_test::serial_sendRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_test::serial_sendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 command\n\
";
  }

  static const char* value(const ::serial_test::serial_sendRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_test::serial_sendRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_sendRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_test::serial_sendRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_test::serial_sendRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int16_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_TEST_MESSAGE_SERIAL_SENDREQUEST_H
