// Generated by gencpp from file serial_test/serial_send.msg
// DO NOT EDIT!


#ifndef SERIAL_TEST_MESSAGE_SERIAL_SEND_H
#define SERIAL_TEST_MESSAGE_SERIAL_SEND_H

#include <ros/service_traits.h>


#include <serial_test/serial_sendRequest.h>
#include <serial_test/serial_sendResponse.h>


namespace serial_test
{

struct serial_send
{

typedef serial_sendRequest Request;
typedef serial_sendResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct serial_send
} // namespace serial_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serial_test::serial_send > {
  static const char* value()
  {
    return "4a85f0858e5941ef92944e5dd453320b";
  }

  static const char* value(const ::serial_test::serial_send&) { return value(); }
};

template<>
struct DataType< ::serial_test::serial_send > {
  static const char* value()
  {
    return "serial_test/serial_send";
  }

  static const char* value(const ::serial_test::serial_send&) { return value(); }
};


// service_traits::MD5Sum< ::serial_test::serial_sendRequest> should match 
// service_traits::MD5Sum< ::serial_test::serial_send > 
template<>
struct MD5Sum< ::serial_test::serial_sendRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serial_test::serial_send >::value();
  }
  static const char* value(const ::serial_test::serial_sendRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_test::serial_sendRequest> should match 
// service_traits::DataType< ::serial_test::serial_send > 
template<>
struct DataType< ::serial_test::serial_sendRequest>
{
  static const char* value()
  {
    return DataType< ::serial_test::serial_send >::value();
  }
  static const char* value(const ::serial_test::serial_sendRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serial_test::serial_sendResponse> should match 
// service_traits::MD5Sum< ::serial_test::serial_send > 
template<>
struct MD5Sum< ::serial_test::serial_sendResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serial_test::serial_send >::value();
  }
  static const char* value(const ::serial_test::serial_sendResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_test::serial_sendResponse> should match 
// service_traits::DataType< ::serial_test::serial_send > 
template<>
struct DataType< ::serial_test::serial_sendResponse>
{
  static const char* value()
  {
    return DataType< ::serial_test::serial_send >::value();
  }
  static const char* value(const ::serial_test::serial_sendResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_TEST_MESSAGE_SERIAL_SEND_H
