(cl:defpackage serial_test-srv
  (:use )
  (:export
   "SERIALSEND"
   "<SERIALSEND-REQUEST>"
   "SERIALSEND-REQUEST"
   "<SERIALSEND-RESPONSE>"
   "SERIALSEND-RESPONSE"
   "SERIAL_READ"
   "<SERIAL_READ-REQUEST>"
   "SERIAL_READ-REQUEST"
   "<SERIAL_READ-RESPONSE>"
   "SERIAL_READ-RESPONSE"
  ))

