// Generated by gencpp from file return_control/SerialSendResponse.msg
// DO NOT EDIT!


#ifndef RETURN_CONTROL_MESSAGE_SERIALSENDRESPONSE_H
#define RETURN_CONTROL_MESSAGE_SERIALSENDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace return_control
{
template <class ContainerAllocator>
struct SerialSendResponse_
{
  typedef SerialSendResponse_<ContainerAllocator> Type;

  SerialSendResponse_()
    : ack(0)  {
    }
  SerialSendResponse_(const ContainerAllocator& _alloc)
    : ack(0)  {
  (void)_alloc;
    }



   typedef int16_t _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::return_control::SerialSendResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::return_control::SerialSendResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SerialSendResponse_

typedef ::return_control::SerialSendResponse_<std::allocator<void> > SerialSendResponse;

typedef boost::shared_ptr< ::return_control::SerialSendResponse > SerialSendResponsePtr;
typedef boost::shared_ptr< ::return_control::SerialSendResponse const> SerialSendResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::return_control::SerialSendResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::return_control::SerialSendResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace return_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'return_control': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/return_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::return_control::SerialSendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::return_control::SerialSendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::return_control::SerialSendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::return_control::SerialSendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::return_control::SerialSendResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::return_control::SerialSendResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::return_control::SerialSendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efd27fb04e2a6ce3c9ff1f47eb32e7bb";
  }

  static const char* value(const ::return_control::SerialSendResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefd27fb04e2a6ce3ULL;
  static const uint64_t static_value2 = 0xc9ff1f47eb32e7bbULL;
};

template<class ContainerAllocator>
struct DataType< ::return_control::SerialSendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "return_control/SerialSendResponse";
  }

  static const char* value(const ::return_control::SerialSendResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::return_control::SerialSendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ack\n\
\n\
";
  }

  static const char* value(const ::return_control::SerialSendResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::return_control::SerialSendResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialSendResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::return_control::SerialSendResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::return_control::SerialSendResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RETURN_CONTROL_MESSAGE_SERIALSENDRESPONSE_H
