// Generated by gencpp from file return_control/SerialSendRequest.msg
// DO NOT EDIT!


#ifndef RETURN_CONTROL_MESSAGE_SERIALSENDREQUEST_H
#define RETURN_CONTROL_MESSAGE_SERIALSENDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace return_control
{
template <class ContainerAllocator>
struct SerialSendRequest_
{
  typedef SerialSendRequest_<ContainerAllocator> Type;

  SerialSendRequest_()
    : command()
    , values()  {
    }
  SerialSendRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::return_control::SerialSendRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::return_control::SerialSendRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SerialSendRequest_

typedef ::return_control::SerialSendRequest_<std::allocator<void> > SerialSendRequest;

typedef boost::shared_ptr< ::return_control::SerialSendRequest > SerialSendRequestPtr;
typedef boost::shared_ptr< ::return_control::SerialSendRequest const> SerialSendRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::return_control::SerialSendRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::return_control::SerialSendRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace return_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'return_control': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/return_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::return_control::SerialSendRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::return_control::SerialSendRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::return_control::SerialSendRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::return_control::SerialSendRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::return_control::SerialSendRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::return_control::SerialSendRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::return_control::SerialSendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95aa4e3087fe2672bbf76af677eaf213";
  }

  static const char* value(const ::return_control::SerialSendRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95aa4e3087fe2672ULL;
  static const uint64_t static_value2 = 0xbbf76af677eaf213ULL;
};

template<class ContainerAllocator>
struct DataType< ::return_control::SerialSendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "return_control/SerialSendRequest";
  }

  static const char* value(const ::return_control::SerialSendRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::return_control::SerialSendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
float32[] values\n\
";
  }

  static const char* value(const ::return_control::SerialSendRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::return_control::SerialSendRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialSendRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::return_control::SerialSendRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::return_control::SerialSendRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RETURN_CONTROL_MESSAGE_SERIALSENDREQUEST_H
