// Generated by gencpp from file return_control/serial_readRequest.msg
// DO NOT EDIT!


#ifndef RETURN_CONTROL_MESSAGE_SERIAL_READREQUEST_H
#define RETURN_CONTROL_MESSAGE_SERIAL_READREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace return_control
{
template <class ContainerAllocator>
struct serial_readRequest_
{
  typedef serial_readRequest_<ContainerAllocator> Type;

  serial_readRequest_()
    {
    }
  serial_readRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::return_control::serial_readRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::return_control::serial_readRequest_<ContainerAllocator> const> ConstPtr;

}; // struct serial_readRequest_

typedef ::return_control::serial_readRequest_<std::allocator<void> > serial_readRequest;

typedef boost::shared_ptr< ::return_control::serial_readRequest > serial_readRequestPtr;
typedef boost::shared_ptr< ::return_control::serial_readRequest const> serial_readRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::return_control::serial_readRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::return_control::serial_readRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace return_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'return_control': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/return_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::return_control::serial_readRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::return_control::serial_readRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::return_control::serial_readRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::return_control::serial_readRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::return_control::serial_readRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::return_control::serial_readRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::return_control::serial_readRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::return_control::serial_readRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::return_control::serial_readRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "return_control/serial_readRequest";
  }

  static const char* value(const ::return_control::serial_readRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::return_control::serial_readRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::return_control::serial_readRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::return_control::serial_readRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_readRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::return_control::serial_readRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::return_control::serial_readRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RETURN_CONTROL_MESSAGE_SERIAL_READREQUEST_H
