// Generated by gencpp from file return_control/setpoint.msg
// DO NOT EDIT!


#ifndef RETURN_CONTROL_MESSAGE_SETPOINT_H
#define RETURN_CONTROL_MESSAGE_SETPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace return_control
{
template <class ContainerAllocator>
struct setpoint_
{
  typedef setpoint_<ContainerAllocator> Type;

  setpoint_()
    : setpoint(0.0)
    , time(0.0)  {
    }
  setpoint_(const ContainerAllocator& _alloc)
    : setpoint(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef float _setpoint_type;
  _setpoint_type setpoint;

   typedef float _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::return_control::setpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::return_control::setpoint_<ContainerAllocator> const> ConstPtr;

}; // struct setpoint_

typedef ::return_control::setpoint_<std::allocator<void> > setpoint;

typedef boost::shared_ptr< ::return_control::setpoint > setpointPtr;
typedef boost::shared_ptr< ::return_control::setpoint const> setpointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::return_control::setpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::return_control::setpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace return_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'return_control': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/return_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::return_control::setpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::return_control::setpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::return_control::setpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::return_control::setpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::return_control::setpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::return_control::setpoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::return_control::setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69dccf7b66123a7863bfbf542606a1d6";
  }

  static const char* value(const ::return_control::setpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69dccf7b66123a78ULL;
  static const uint64_t static_value2 = 0x63bfbf542606a1d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::return_control::setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "return_control/setpoint";
  }

  static const char* value(const ::return_control::setpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::return_control::setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 setpoint\n\
float32 time\n\
\n\
\n\
";
  }

  static const char* value(const ::return_control::setpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::return_control::setpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setpoint);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::return_control::setpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::return_control::setpoint_<ContainerAllocator>& v)
  {
    s << indent << "setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.setpoint);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RETURN_CONTROL_MESSAGE_SETPOINT_H
