// Generated by gencpp from file gantry_control/currPos.msg
// DO NOT EDIT!


#ifndef GANTRY_CONTROL_MESSAGE_CURRPOS_H
#define GANTRY_CONTROL_MESSAGE_CURRPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gantry_control
{
template <class ContainerAllocator>
struct currPos_
{
  typedef currPos_<ContainerAllocator> Type;

  currPos_()
    : position()  {
    }
  currPos_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::gantry_control::currPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gantry_control::currPos_<ContainerAllocator> const> ConstPtr;

}; // struct currPos_

typedef ::gantry_control::currPos_<std::allocator<void> > currPos;

typedef boost::shared_ptr< ::gantry_control::currPos > currPosPtr;
typedef boost::shared_ptr< ::gantry_control::currPos const> currPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gantry_control::currPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gantry_control::currPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gantry_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'gantry_control': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/gantry_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gantry_control::currPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gantry_control::currPos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gantry_control::currPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gantry_control::currPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gantry_control::currPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gantry_control::currPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gantry_control::currPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ec164ae840396df197eeb512c1b8515";
  }

  static const char* value(const ::gantry_control::currPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ec164ae840396dfULL;
  static const uint64_t static_value2 = 0x197eeb512c1b8515ULL;
};

template<class ContainerAllocator>
struct DataType< ::gantry_control::currPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gantry_control/currPos";
  }

  static const char* value(const ::gantry_control::currPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gantry_control::currPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] position\n\
";
  }

  static const char* value(const ::gantry_control::currPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gantry_control::currPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct currPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gantry_control::currPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gantry_control::currPos_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GANTRY_CONTROL_MESSAGE_CURRPOS_H
