// Generated by gencpp from file gantry_control/from_gantry.msg
// DO NOT EDIT!


#ifndef GANTRY_CONTROL_MESSAGE_FROM_GANTRY_H
#define GANTRY_CONTROL_MESSAGE_FROM_GANTRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gantry_control
{
template <class ContainerAllocator>
struct from_gantry_
{
  typedef from_gantry_<ContainerAllocator> Type;

  from_gantry_()
    : response()
    , position()  {
    }
  from_gantry_(const ContainerAllocator& _alloc)
    : response(_alloc)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::gantry_control::from_gantry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gantry_control::from_gantry_<ContainerAllocator> const> ConstPtr;

}; // struct from_gantry_

typedef ::gantry_control::from_gantry_<std::allocator<void> > from_gantry;

typedef boost::shared_ptr< ::gantry_control::from_gantry > from_gantryPtr;
typedef boost::shared_ptr< ::gantry_control::from_gantry const> from_gantryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gantry_control::from_gantry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gantry_control::from_gantry_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gantry_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'gantry_control': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/gantry_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gantry_control::from_gantry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gantry_control::from_gantry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gantry_control::from_gantry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gantry_control::from_gantry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gantry_control::from_gantry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gantry_control::from_gantry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gantry_control::from_gantry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "462b18e0de79f571e404f9b05e3ff8d0";
  }

  static const char* value(const ::gantry_control::from_gantry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x462b18e0de79f571ULL;
  static const uint64_t static_value2 = 0xe404f9b05e3ff8d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::gantry_control::from_gantry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gantry_control/from_gantry";
  }

  static const char* value(const ::gantry_control::from_gantry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gantry_control::from_gantry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n\
float32[] position\n\
";
  }

  static const char* value(const ::gantry_control::from_gantry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gantry_control::from_gantry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct from_gantry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gantry_control::from_gantry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gantry_control::from_gantry_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GANTRY_CONTROL_MESSAGE_FROM_GANTRY_H
