// Generated by gencpp from file gantry_control/gantry_send.msg
// DO NOT EDIT!


#ifndef GANTRY_CONTROL_MESSAGE_GANTRY_SEND_H
#define GANTRY_CONTROL_MESSAGE_GANTRY_SEND_H

#include <ros/service_traits.h>


#include <gantry_control/gantry_sendRequest.h>
#include <gantry_control/gantry_sendResponse.h>


namespace gantry_control
{

struct gantry_send
{

typedef gantry_sendRequest Request;
typedef gantry_sendResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gantry_send
} // namespace gantry_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gantry_control::gantry_send > {
  static const char* value()
  {
    return "21afae2465c27c8fc1d2797f773bd384";
  }

  static const char* value(const ::gantry_control::gantry_send&) { return value(); }
};

template<>
struct DataType< ::gantry_control::gantry_send > {
  static const char* value()
  {
    return "gantry_control/gantry_send";
  }

  static const char* value(const ::gantry_control::gantry_send&) { return value(); }
};


// service_traits::MD5Sum< ::gantry_control::gantry_sendRequest> should match 
// service_traits::MD5Sum< ::gantry_control::gantry_send > 
template<>
struct MD5Sum< ::gantry_control::gantry_sendRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gantry_control::gantry_send >::value();
  }
  static const char* value(const ::gantry_control::gantry_sendRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gantry_control::gantry_sendRequest> should match 
// service_traits::DataType< ::gantry_control::gantry_send > 
template<>
struct DataType< ::gantry_control::gantry_sendRequest>
{
  static const char* value()
  {
    return DataType< ::gantry_control::gantry_send >::value();
  }
  static const char* value(const ::gantry_control::gantry_sendRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gantry_control::gantry_sendResponse> should match 
// service_traits::MD5Sum< ::gantry_control::gantry_send > 
template<>
struct MD5Sum< ::gantry_control::gantry_sendResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gantry_control::gantry_send >::value();
  }
  static const char* value(const ::gantry_control::gantry_sendResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gantry_control::gantry_sendResponse> should match 
// service_traits::DataType< ::gantry_control::gantry_send > 
template<>
struct DataType< ::gantry_control::gantry_sendResponse>
{
  static const char* value()
  {
    return DataType< ::gantry_control::gantry_send >::value();
  }
  static const char* value(const ::gantry_control::gantry_sendResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GANTRY_CONTROL_MESSAGE_GANTRY_SEND_H
