// Generated by gencpp from file gantry_control/gantry_sendResponse.msg
// DO NOT EDIT!


#ifndef GANTRY_CONTROL_MESSAGE_GANTRY_SENDRESPONSE_H
#define GANTRY_CONTROL_MESSAGE_GANTRY_SENDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gantry_control
{
template <class ContainerAllocator>
struct gantry_sendResponse_
{
  typedef gantry_sendResponse_<ContainerAllocator> Type;

  gantry_sendResponse_()
    : ack(0)  {
    }
  gantry_sendResponse_(const ContainerAllocator& _alloc)
    : ack(0)  {
  (void)_alloc;
    }



   typedef int16_t _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::gantry_control::gantry_sendResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gantry_control::gantry_sendResponse_<ContainerAllocator> const> ConstPtr;

}; // struct gantry_sendResponse_

typedef ::gantry_control::gantry_sendResponse_<std::allocator<void> > gantry_sendResponse;

typedef boost::shared_ptr< ::gantry_control::gantry_sendResponse > gantry_sendResponsePtr;
typedef boost::shared_ptr< ::gantry_control::gantry_sendResponse const> gantry_sendResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gantry_control::gantry_sendResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gantry_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gantry_control': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/gantry_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gantry_control::gantry_sendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gantry_control::gantry_sendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gantry_control::gantry_sendResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efd27fb04e2a6ce3c9ff1f47eb32e7bb";
  }

  static const char* value(const ::gantry_control::gantry_sendResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefd27fb04e2a6ce3ULL;
  static const uint64_t static_value2 = 0xc9ff1f47eb32e7bbULL;
};

template<class ContainerAllocator>
struct DataType< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gantry_control/gantry_sendResponse";
  }

  static const char* value(const ::gantry_control::gantry_sendResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ack\n\
\n\
";
  }

  static const char* value(const ::gantry_control::gantry_sendResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gantry_sendResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gantry_control::gantry_sendResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gantry_control::gantry_sendResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GANTRY_CONTROL_MESSAGE_GANTRY_SENDRESPONSE_H
