// Generated by gencpp from file gantry_control/gantry_sendRequest.msg
// DO NOT EDIT!


#ifndef GANTRY_CONTROL_MESSAGE_GANTRY_SENDREQUEST_H
#define GANTRY_CONTROL_MESSAGE_GANTRY_SENDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gantry_control
{
template <class ContainerAllocator>
struct gantry_sendRequest_
{
  typedef gantry_sendRequest_<ContainerAllocator> Type;

  gantry_sendRequest_()
    : command()
    , type()
    , path()  {
    }
  gantry_sendRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , type(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::gantry_control::gantry_sendRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gantry_control::gantry_sendRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gantry_sendRequest_

typedef ::gantry_control::gantry_sendRequest_<std::allocator<void> > gantry_sendRequest;

typedef boost::shared_ptr< ::gantry_control::gantry_sendRequest > gantry_sendRequestPtr;
typedef boost::shared_ptr< ::gantry_control::gantry_sendRequest const> gantry_sendRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gantry_control::gantry_sendRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gantry_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'gantry_control': ['/media/woodlab/DATAPART1/watertank-gantry/ROS/catkin_ws/src/gantry_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gantry_control::gantry_sendRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gantry_control::gantry_sendRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gantry_control::gantry_sendRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c395f0dfc1ed9431de3df8847a8f9592";
  }

  static const char* value(const ::gantry_control::gantry_sendRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc395f0dfc1ed9431ULL;
  static const uint64_t static_value2 = 0xde3df8847a8f9592ULL;
};

template<class ContainerAllocator>
struct DataType< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gantry_control/gantry_sendRequest";
  }

  static const char* value(const ::gantry_control::gantry_sendRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
string type\n\
string path\n\
";
  }

  static const char* value(const ::gantry_control::gantry_sendRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.type);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gantry_sendRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gantry_control::gantry_sendRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gantry_control::gantry_sendRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GANTRY_CONTROL_MESSAGE_GANTRY_SENDREQUEST_H
